# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from workspace.v1 import client_storage_pb2 as workspace_dot_v1_dot_client__storage__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workspace/v1/client_storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientStorageServiceStub(object):
    """ClientStorageService — Client reverse-stream connection service.
    Client connects to Server and serves file operations on its local directory.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/workspace.v1.ClientStorageService/Connect',
                request_serializer=workspace_dot_v1_dot_client__storage__pb2.ClientMessage.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_client__storage__pb2.ServerStorageMessage.FromString,
                _registered_method=True)
        self.ReadFileStream = channel.stream_unary(
                '/workspace.v1.ClientStorageService/ReadFileStream',
                request_serializer=workspace_dot_v1_dot_client__storage__pb2.ReadFileStreamRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_client__storage__pb2.ReadFileStreamResponse.FromString,
                _registered_method=True)
        self.WriteFileStream = channel.unary_stream(
                '/workspace.v1.ClientStorageService/WriteFileStream',
                request_serializer=workspace_dot_v1_dot_client__storage__pb2.WriteFileStreamRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_client__storage__pb2.WriteFileStreamResponse.FromString,
                _registered_method=True)


class ClientStorageServiceServicer(object):
    """ClientStorageService — Client reverse-stream connection service.
    Client connects to Server and serves file operations on its local directory.
    """

    def Connect(self, request_iterator, context):
        """Control stream: bidirectional, carries metadata operations and heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFileStream(self, request_iterator, context):
        """Data stream: Client reads local file and streams to Server (client-streaming)
        Data direction: Client -> Server (file content from Client local disk to Server)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFileStream(self, request, context):
        """Data stream: Server streams data to Client for writing (server-streaming)
        Data direction: Server -> Client (file content from Server to Client local disk)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=workspace_dot_v1_dot_client__storage__pb2.ClientMessage.FromString,
                    response_serializer=workspace_dot_v1_dot_client__storage__pb2.ServerStorageMessage.SerializeToString,
            ),
            'ReadFileStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ReadFileStream,
                    request_deserializer=workspace_dot_v1_dot_client__storage__pb2.ReadFileStreamRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_client__storage__pb2.ReadFileStreamResponse.SerializeToString,
            ),
            'WriteFileStream': grpc.unary_stream_rpc_method_handler(
                    servicer.WriteFileStream,
                    request_deserializer=workspace_dot_v1_dot_client__storage__pb2.WriteFileStreamRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_client__storage__pb2.WriteFileStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workspace.v1.ClientStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workspace.v1.ClientStorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientStorageService(object):
    """ClientStorageService — Client reverse-stream connection service.
    Client connects to Server and serves file operations on its local directory.
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/workspace.v1.ClientStorageService/Connect',
            workspace_dot_v1_dot_client__storage__pb2.ClientMessage.SerializeToString,
            workspace_dot_v1_dot_client__storage__pb2.ServerStorageMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFileStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/workspace.v1.ClientStorageService/ReadFileStream',
            workspace_dot_v1_dot_client__storage__pb2.ReadFileStreamRequest.SerializeToString,
            workspace_dot_v1_dot_client__storage__pb2.ReadFileStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFileStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/workspace.v1.ClientStorageService/WriteFileStream',
            workspace_dot_v1_dot_client__storage__pb2.WriteFileStreamRequest.SerializeToString,
            workspace_dot_v1_dot_client__storage__pb2.WriteFileStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
