# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import filesystem_pb2 as workspace_dot_v1_dot_filesystem__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workspace/v1/filesystem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileSystemServiceStub(object):
    """FileSystemService provides complete POSIX-like filesystem operations
    for FUSE clients to mount remote workspaces as local directories.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stat = channel.unary_unary(
                '/workspace.v1.FileSystemService/Stat',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsStatRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsStatResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_stream(
                '/workspace.v1.FileSystemService/ReadFile',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsReadFileRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsReadFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.stream_unary(
                '/workspace.v1.FileSystemService/WriteFile',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsWriteFileRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsWriteFileResponse.FromString,
                _registered_method=True)
        self.ListDir = channel.unary_stream(
                '/workspace.v1.FileSystemService/ListDir',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsListDirRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsListDirResponse.FromString,
                _registered_method=True)
        self.Mkdir = channel.unary_unary(
                '/workspace.v1.FileSystemService/Mkdir',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsMkdirRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsMkdirResponse.FromString,
                _registered_method=True)
        self.RemoveFile = channel.unary_unary(
                '/workspace.v1.FileSystemService/RemoveFile',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsRemoveFileRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsRemoveFileResponse.FromString,
                _registered_method=True)
        self.RemoveDir = channel.unary_unary(
                '/workspace.v1.FileSystemService/RemoveDir',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsRemoveDirRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsRemoveDirResponse.FromString,
                _registered_method=True)
        self.Rename = channel.unary_unary(
                '/workspace.v1.FileSystemService/Rename',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsRenameRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsRenameResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/workspace.v1.FileSystemService/Create',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsCreateRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsCreateResponse.FromString,
                _registered_method=True)
        self.SetAttr = channel.unary_unary(
                '/workspace.v1.FileSystemService/SetAttr',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsSetAttrRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsSetAttrResponse.FromString,
                _registered_method=True)
        self.Symlink = channel.unary_unary(
                '/workspace.v1.FileSystemService/Symlink',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsSymlinkRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsSymlinkResponse.FromString,
                _registered_method=True)
        self.ReadLink = channel.unary_unary(
                '/workspace.v1.FileSystemService/ReadLink',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsReadLinkRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsReadLinkResponse.FromString,
                _registered_method=True)
        self.ReadAt = channel.unary_unary(
                '/workspace.v1.FileSystemService/ReadAt',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsReadAtRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsReadAtResponse.FromString,
                _registered_method=True)
        self.WriteAt = channel.unary_unary(
                '/workspace.v1.FileSystemService/WriteAt',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsWriteAtRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsWriteAtResponse.FromString,
                _registered_method=True)
        self.StatFs = channel.unary_unary(
                '/workspace.v1.FileSystemService/StatFs',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.FsStatFsRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsStatFsResponse.FromString,
                _registered_method=True)
        self.DownloadBinary = channel.unary_stream(
                '/workspace.v1.FileSystemService/DownloadBinary',
                request_serializer=workspace_dot_v1_dot_filesystem__pb2.DownloadBinaryRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_filesystem__pb2.DownloadBinaryResponse.FromString,
                _registered_method=True)


class FileSystemServiceServicer(object):
    """FileSystemService provides complete POSIX-like filesystem operations
    for FUSE clients to mount remote workspaces as local directories.
    """

    def Stat(self, request, context):
        """Get file/directory metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Read file content (streaming for large files)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request_iterator, context):
        """Write file content (streaming for large files)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDir(self, request, context):
        """List directory contents (streaming for large directories)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mkdir(self, request, context):
        """Create a directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFile(self, request, context):
        """Remove a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDir(self, request, context):
        """Remove a directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """Rename or move a file/directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Create a new file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAttr(self, request, context):
        """Set file attributes (size, mode, times)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Symlink(self, request, context):
        """Create a symbolic link
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadLink(self, request, context):
        """Read symbolic link target
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAt(self, request, context):
        """Read file at specific offset (random access)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteAt(self, request, context):
        """Write file at specific offset (random access)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatFs(self, request, context):
        """Get filesystem statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadBinary(self, request, context):
        """Download binary file (e.g., workspace-fuse)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileSystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsStatRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsStatResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsReadFileRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsReadFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsWriteFileRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsWriteFileResponse.SerializeToString,
            ),
            'ListDir': grpc.unary_stream_rpc_method_handler(
                    servicer.ListDir,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsListDirRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsListDirResponse.SerializeToString,
            ),
            'Mkdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkdir,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsMkdirRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsMkdirResponse.SerializeToString,
            ),
            'RemoveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFile,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsRemoveFileRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsRemoveFileResponse.SerializeToString,
            ),
            'RemoveDir': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDir,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsRemoveDirRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsRemoveDirResponse.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsRenameRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsRenameResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsCreateRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsCreateResponse.SerializeToString,
            ),
            'SetAttr': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAttr,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsSetAttrRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsSetAttrResponse.SerializeToString,
            ),
            'Symlink': grpc.unary_unary_rpc_method_handler(
                    servicer.Symlink,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsSymlinkRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsSymlinkResponse.SerializeToString,
            ),
            'ReadLink': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadLink,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsReadLinkRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsReadLinkResponse.SerializeToString,
            ),
            'ReadAt': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadAt,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsReadAtRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsReadAtResponse.SerializeToString,
            ),
            'WriteAt': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteAt,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsWriteAtRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsWriteAtResponse.SerializeToString,
            ),
            'StatFs': grpc.unary_unary_rpc_method_handler(
                    servicer.StatFs,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.FsStatFsRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.FsStatFsResponse.SerializeToString,
            ),
            'DownloadBinary': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadBinary,
                    request_deserializer=workspace_dot_v1_dot_filesystem__pb2.DownloadBinaryRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_filesystem__pb2.DownloadBinaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workspace.v1.FileSystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workspace.v1.FileSystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileSystemService(object):
    """FileSystemService provides complete POSIX-like filesystem operations
    for FUSE clients to mount remote workspaces as local directories.
    """

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/Stat',
            workspace_dot_v1_dot_filesystem__pb2.FsStatRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsStatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/workspace.v1.FileSystemService/ReadFile',
            workspace_dot_v1_dot_filesystem__pb2.FsReadFileRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/workspace.v1.FileSystemService/WriteFile',
            workspace_dot_v1_dot_filesystem__pb2.FsWriteFileRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsWriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/workspace.v1.FileSystemService/ListDir',
            workspace_dot_v1_dot_filesystem__pb2.FsListDirRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsListDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mkdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/Mkdir',
            workspace_dot_v1_dot_filesystem__pb2.FsMkdirRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsMkdirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/RemoveFile',
            workspace_dot_v1_dot_filesystem__pb2.FsRemoveFileRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsRemoveFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/RemoveDir',
            workspace_dot_v1_dot_filesystem__pb2.FsRemoveDirRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsRemoveDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/Rename',
            workspace_dot_v1_dot_filesystem__pb2.FsRenameRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsRenameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/Create',
            workspace_dot_v1_dot_filesystem__pb2.FsCreateRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAttr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/SetAttr',
            workspace_dot_v1_dot_filesystem__pb2.FsSetAttrRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsSetAttrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Symlink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/Symlink',
            workspace_dot_v1_dot_filesystem__pb2.FsSymlinkRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsSymlinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/ReadLink',
            workspace_dot_v1_dot_filesystem__pb2.FsReadLinkRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsReadLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadAt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/ReadAt',
            workspace_dot_v1_dot_filesystem__pb2.FsReadAtRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsReadAtResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteAt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/WriteAt',
            workspace_dot_v1_dot_filesystem__pb2.FsWriteAtRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsWriteAtResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatFs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.FileSystemService/StatFs',
            workspace_dot_v1_dot_filesystem__pb2.FsStatFsRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.FsStatFsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/workspace.v1.FileSystemService/DownloadBinary',
            workspace_dot_v1_dot_filesystem__pb2.DownloadBinaryRequest.SerializeToString,
            workspace_dot_v1_dot_filesystem__pb2.DownloadBinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
