# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from workspace.v1 import process_pb2 as workspace_dot_v1_dot_process__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workspace/v1/process_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProcessServiceStub(object):
    """Process service for executing commands in sandboxes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunCommand = channel.unary_unary(
                '/workspace.v1.ProcessService/RunCommand',
                request_serializer=workspace_dot_v1_dot_process__pb2.RunCommandRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_process__pb2.RunCommandResponse.FromString,
                _registered_method=True)
        self.RunCommandStream = channel.unary_stream(
                '/workspace.v1.ProcessService/RunCommandStream',
                request_serializer=workspace_dot_v1_dot_process__pb2.RunCommandRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_process__pb2.ProcessEvent.FromString,
                _registered_method=True)
        self.KillProcess = channel.unary_unary(
                '/workspace.v1.ProcessService/KillProcess',
                request_serializer=workspace_dot_v1_dot_process__pb2.KillProcessRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_process__pb2.KillProcessResponse.FromString,
                _registered_method=True)


class ProcessServiceServicer(object):
    """Process service for executing commands in sandboxes
    """

    def RunCommand(self, request, context):
        """Run a command and wait for completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunCommandStream(self, request, context):
        """Run a command with streaming output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillProcess(self, request, context):
        """Kill a running process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCommand,
                    request_deserializer=workspace_dot_v1_dot_process__pb2.RunCommandRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_process__pb2.RunCommandResponse.SerializeToString,
            ),
            'RunCommandStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RunCommandStream,
                    request_deserializer=workspace_dot_v1_dot_process__pb2.RunCommandRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_process__pb2.ProcessEvent.SerializeToString,
            ),
            'KillProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.KillProcess,
                    request_deserializer=workspace_dot_v1_dot_process__pb2.KillProcessRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_process__pb2.KillProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workspace.v1.ProcessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workspace.v1.ProcessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessService(object):
    """Process service for executing commands in sandboxes
    """

    @staticmethod
    def RunCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.ProcessService/RunCommand',
            workspace_dot_v1_dot_process__pb2.RunCommandRequest.SerializeToString,
            workspace_dot_v1_dot_process__pb2.RunCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunCommandStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/workspace.v1.ProcessService/RunCommandStream',
            workspace_dot_v1_dot_process__pb2.RunCommandRequest.SerializeToString,
            workspace_dot_v1_dot_process__pb2.ProcessEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KillProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.ProcessService/KillProcess',
            workspace_dot_v1_dot_process__pb2.KillProcessRequest.SerializeToString,
            workspace_dot_v1_dot_process__pb2.KillProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
