# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pty_pb2 as workspace_dot_v1_dot_pty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workspace/v1/pty_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PtyServiceStub(object):
    """PTY service for interactive terminal sessions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePty = channel.unary_unary(
                '/workspace.v1.PtyService/CreatePty',
                request_serializer=workspace_dot_v1_dot_pty__pb2.CreatePtyRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_pty__pb2.CreatePtyResponse.FromString,
                _registered_method=True)
        self.ResizePty = channel.unary_unary(
                '/workspace.v1.PtyService/ResizePty',
                request_serializer=workspace_dot_v1_dot_pty__pb2.ResizePtyRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_pty__pb2.ResizePtyResponse.FromString,
                _registered_method=True)
        self.KillPty = channel.unary_unary(
                '/workspace.v1.PtyService/KillPty',
                request_serializer=workspace_dot_v1_dot_pty__pb2.KillPtyRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_pty__pb2.KillPtyResponse.FromString,
                _registered_method=True)
        self.PtyStream = channel.stream_stream(
                '/workspace.v1.PtyService/PtyStream',
                request_serializer=workspace_dot_v1_dot_pty__pb2.PtyStreamRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_pty__pb2.PtyStreamResponse.FromString,
                _registered_method=True)


class PtyServiceServicer(object):
    """PTY service for interactive terminal sessions
    """

    def CreatePty(self, request, context):
        """Create a new PTY
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResizePty(self, request, context):
        """Resize a PTY
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillPty(self, request, context):
        """Kill a PTY
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PtyStream(self, request_iterator, context):
        """Bidirectional stream for PTY I/O
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PtyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePty': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePty,
                    request_deserializer=workspace_dot_v1_dot_pty__pb2.CreatePtyRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_pty__pb2.CreatePtyResponse.SerializeToString,
            ),
            'ResizePty': grpc.unary_unary_rpc_method_handler(
                    servicer.ResizePty,
                    request_deserializer=workspace_dot_v1_dot_pty__pb2.ResizePtyRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_pty__pb2.ResizePtyResponse.SerializeToString,
            ),
            'KillPty': grpc.unary_unary_rpc_method_handler(
                    servicer.KillPty,
                    request_deserializer=workspace_dot_v1_dot_pty__pb2.KillPtyRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_pty__pb2.KillPtyResponse.SerializeToString,
            ),
            'PtyStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PtyStream,
                    request_deserializer=workspace_dot_v1_dot_pty__pb2.PtyStreamRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_pty__pb2.PtyStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workspace.v1.PtyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workspace.v1.PtyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PtyService(object):
    """PTY service for interactive terminal sessions
    """

    @staticmethod
    def CreatePty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.PtyService/CreatePty',
            workspace_dot_v1_dot_pty__pb2.CreatePtyRequest.SerializeToString,
            workspace_dot_v1_dot_pty__pb2.CreatePtyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResizePty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.PtyService/ResizePty',
            workspace_dot_v1_dot_pty__pb2.ResizePtyRequest.SerializeToString,
            workspace_dot_v1_dot_pty__pb2.ResizePtyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KillPty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.PtyService/KillPty',
            workspace_dot_v1_dot_pty__pb2.KillPtyRequest.SerializeToString,
            workspace_dot_v1_dot_pty__pb2.KillPtyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PtyStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/workspace.v1.PtyService/PtyStream',
            workspace_dot_v1_dot_pty__pb2.PtyStreamRequest.SerializeToString,
            workspace_dot_v1_dot_pty__pb2.PtyStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
