# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from workspace_sdk.proto.workspace.v1 import sandbox_pb2 as workspace_dot_v1_dot_sandbox__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workspace/v1/sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub(object):
    """Sandbox service for managing sandbox lifecycle
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSandbox = channel.unary_unary(
                '/workspace.v1.SandboxService/CreateSandbox',
                request_serializer=workspace_dot_v1_dot_sandbox__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_sandbox__pb2.CreateSandboxResponse.FromString,
                _registered_method=True)
        self.GetSandbox = channel.unary_unary(
                '/workspace.v1.SandboxService/GetSandbox',
                request_serializer=workspace_dot_v1_dot_sandbox__pb2.GetSandboxRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_sandbox__pb2.GetSandboxResponse.FromString,
                _registered_method=True)
        self.ListSandboxes = channel.unary_unary(
                '/workspace.v1.SandboxService/ListSandboxes',
                request_serializer=workspace_dot_v1_dot_sandbox__pb2.ListSandboxesRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_sandbox__pb2.ListSandboxesResponse.FromString,
                _registered_method=True)
        self.DeleteSandbox = channel.unary_unary(
                '/workspace.v1.SandboxService/DeleteSandbox',
                request_serializer=workspace_dot_v1_dot_sandbox__pb2.DeleteSandboxRequest.SerializeToString,
                response_deserializer=workspace_dot_v1_dot_sandbox__pb2.DeleteSandboxResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """Sandbox service for managing sandbox lifecycle
    """

    def CreateSandbox(self, request, context):
        """Create a new sandbox
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandbox(self, request, context):
        """Get sandbox by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSandboxes(self, request, context):
        """List all sandboxes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandbox(self, request, context):
        """Delete a sandbox
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=workspace_dot_v1_dot_sandbox__pb2.CreateSandboxRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_sandbox__pb2.CreateSandboxResponse.SerializeToString,
            ),
            'GetSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandbox,
                    request_deserializer=workspace_dot_v1_dot_sandbox__pb2.GetSandboxRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_sandbox__pb2.GetSandboxResponse.SerializeToString,
            ),
            'ListSandboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxes,
                    request_deserializer=workspace_dot_v1_dot_sandbox__pb2.ListSandboxesRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_sandbox__pb2.ListSandboxesResponse.SerializeToString,
            ),
            'DeleteSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandbox,
                    request_deserializer=workspace_dot_v1_dot_sandbox__pb2.DeleteSandboxRequest.FromString,
                    response_serializer=workspace_dot_v1_dot_sandbox__pb2.DeleteSandboxResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workspace.v1.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workspace.v1.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """Sandbox service for managing sandbox lifecycle
    """

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.SandboxService/CreateSandbox',
            workspace_dot_v1_dot_sandbox__pb2.CreateSandboxRequest.SerializeToString,
            workspace_dot_v1_dot_sandbox__pb2.CreateSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.SandboxService/GetSandbox',
            workspace_dot_v1_dot_sandbox__pb2.GetSandboxRequest.SerializeToString,
            workspace_dot_v1_dot_sandbox__pb2.GetSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.SandboxService/ListSandboxes',
            workspace_dot_v1_dot_sandbox__pb2.ListSandboxesRequest.SerializeToString,
            workspace_dot_v1_dot_sandbox__pb2.ListSandboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace.v1.SandboxService/DeleteSandbox',
            workspace_dot_v1_dot_sandbox__pb2.DeleteSandboxRequest.SerializeToString,
            workspace_dot_v1_dot_sandbox__pb2.DeleteSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
