//! Build script for compiling protobuf definitions
//!
//! Generates server and client code for workspace proto files.
//! AgentService is compiled separately to avoid client generation naming conflict.

use std::io::Write;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = "src/gen";

    // Ensure output directory exists
    std::fs::create_dir_all(out_dir)?;

    // First: compile all protos EXCEPT agent.proto with both server and client
    tonic_build::configure()
        .build_server(true)
        .build_client(true)
        .out_dir(out_dir)
        .file_descriptor_set_path(format!("{out_dir}/main_descriptor.bin"))
        .compile_protos(
            &[
                "../proto/workspace/v1/sandbox.proto",
                "../proto/workspace/v1/process.proto",
                "../proto/workspace/v1/pty.proto",
                "../proto/workspace/v1/workspace.proto",
                "../proto/workspace/v1/filesystem.proto",
            ],
            &["../proto"],
        )?;

    // Rename the generated file to avoid overwrite
    std::fs::rename(
        format!("{out_dir}/workspace.v1.rs"),
        format!("{out_dir}/main_services.rs"),
    )?;

    // Second: compile agent.proto with server only (no client due to Connect RPC conflict)
    tonic_build::configure()
        .build_server(true)
        .build_client(false)
        .out_dir(out_dir)
        .file_descriptor_set_path(format!("{out_dir}/agent_descriptor.bin"))
        .compile_protos(&["../proto/workspace/v1/agent.proto"], &["../proto"])?;

    // Rename agent services file
    std::fs::rename(
        format!("{out_dir}/workspace.v1.rs"),
        format!("{out_dir}/agent_services.rs"),
    )?;

    // Create a combined module file that includes both
    let mut combined = std::fs::File::create(format!("{out_dir}/workspace.v1.rs"))?;
    writeln!(combined, "// This file is @generated by build.rs")?;
    writeln!(combined)?;
    writeln!(combined, "// Main services (with client support)")?;
    writeln!(combined, "include!(\"main_services.rs\");")?;
    writeln!(combined)?;
    writeln!(
        combined,
        "// Agent service (server only, client disabled due to Connect RPC naming conflict)"
    )?;
    writeln!(combined, "include!(\"agent_services.rs\");")?;

    println!("cargo:rerun-if-changed=../proto");
    Ok(())
}
