// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workspace/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message from agent to server
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentMessage_Handshake
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_CommandResponse
	//	*AgentMessage_PtyOutput
	Message       isAgentMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_workspace_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMessage() isAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentMessage) GetHandshake() *AgentHandshake {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandResponse() *AgentCommandResponse {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_CommandResponse); ok {
			return x.CommandResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetPtyOutput() *AgentPtyOutput {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_PtyOutput); ok {
			return x.PtyOutput
		}
	}
	return nil
}

type isAgentMessage_Message interface {
	isAgentMessage_Message()
}

type AgentMessage_Handshake struct {
	// Initial handshake
	Handshake *AgentHandshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	// Heartbeat
	Heartbeat *AgentHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_CommandResponse struct {
	// Command response
	CommandResponse *AgentCommandResponse `protobuf:"bytes,3,opt,name=command_response,json=commandResponse,proto3,oneof"`
}

type AgentMessage_PtyOutput struct {
	// PTY output
	PtyOutput *AgentPtyOutput `protobuf:"bytes,4,opt,name=pty_output,json=ptyOutput,proto3,oneof"`
}

func (*AgentMessage_Handshake) isAgentMessage_Message() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Message() {}

func (*AgentMessage_CommandResponse) isAgentMessage_Message() {}

func (*AgentMessage_PtyOutput) isAgentMessage_Message() {}

// Agent handshake message
type AgentHandshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox ID this agent belongs to
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Agent version
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHandshake) Reset() {
	*x = AgentHandshake{}
	mi := &file_workspace_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHandshake) ProtoMessage() {}

func (x *AgentHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHandshake.ProtoReflect.Descriptor instead.
func (*AgentHandshake) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentHandshake) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *AgentHandshake) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Agent heartbeat
type AgentHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp in milliseconds
	Timestamp     uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_workspace_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHeartbeat) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Command response from agent
type AgentCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation ID to match request
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*AgentCommandResponse_Success
	//	*AgentCommandResponse_Error
	Result        isAgentCommandResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommandResponse) Reset() {
	*x = AgentCommandResponse{}
	mi := &file_workspace_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommandResponse) ProtoMessage() {}

func (x *AgentCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommandResponse.ProtoReflect.Descriptor instead.
func (*AgentCommandResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentCommandResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentCommandResponse) GetResult() isAgentCommandResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AgentCommandResponse) GetSuccess() *AgentCommandSuccess {
	if x != nil {
		if x, ok := x.Result.(*AgentCommandResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *AgentCommandResponse) GetError() *AgentCommandError {
	if x != nil {
		if x, ok := x.Result.(*AgentCommandResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isAgentCommandResponse_Result interface {
	isAgentCommandResponse_Result()
}

type AgentCommandResponse_Success struct {
	// Successful result
	Success *AgentCommandSuccess `protobuf:"bytes,2,opt,name=success,proto3,oneof"`
}

type AgentCommandResponse_Error struct {
	// Error result
	Error *AgentCommandError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*AgentCommandResponse_Success) isAgentCommandResponse_Result() {}

func (*AgentCommandResponse_Error) isAgentCommandResponse_Result() {}

// Successful command result
type AgentCommandSuccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exit code
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Standard output
	Stdout string `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Standard error
	Stderr        string `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommandSuccess) Reset() {
	*x = AgentCommandSuccess{}
	mi := &file_workspace_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommandSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommandSuccess) ProtoMessage() {}

func (x *AgentCommandSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommandSuccess.ProtoReflect.Descriptor instead.
func (*AgentCommandSuccess) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentCommandSuccess) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *AgentCommandSuccess) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *AgentCommandSuccess) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

// Command error
type AgentCommandError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Error message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommandError) Reset() {
	*x = AgentCommandError{}
	mi := &file_workspace_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommandError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommandError) ProtoMessage() {}

func (x *AgentCommandError) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommandError.ProtoReflect.Descriptor instead.
func (*AgentCommandError) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentCommandError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AgentCommandError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PTY output from agent
type AgentPtyOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PTY ID
	PtyId string `protobuf:"bytes,1,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	// Output data
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPtyOutput) Reset() {
	*x = AgentPtyOutput{}
	mi := &file_workspace_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPtyOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPtyOutput) ProtoMessage() {}

func (x *AgentPtyOutput) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPtyOutput.ProtoReflect.Descriptor instead.
func (*AgentPtyOutput) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentPtyOutput) GetPtyId() string {
	if x != nil {
		return x.PtyId
	}
	return ""
}

func (x *AgentPtyOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Message from server to agent
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_HandshakeAck
	//	*ServerMessage_HeartbeatAck
	//	*ServerMessage_RunCommand
	//	*ServerMessage_KillProcess
	//	*ServerMessage_CreatePty
	//	*ServerMessage_ResizePty
	//	*ServerMessage_KillPty
	//	*ServerMessage_PtyInput
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_workspace_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetHandshakeAck() *ServerHandshakeAck {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_HandshakeAck); ok {
			return x.HandshakeAck
		}
	}
	return nil
}

func (x *ServerMessage) GetHeartbeatAck() *ServerHeartbeatAck {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ServerMessage) GetRunCommand() *AgentRunCommandRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_RunCommand); ok {
			return x.RunCommand
		}
	}
	return nil
}

func (x *ServerMessage) GetKillProcess() *AgentKillProcessRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_KillProcess); ok {
			return x.KillProcess
		}
	}
	return nil
}

func (x *ServerMessage) GetCreatePty() *AgentCreatePtyRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_CreatePty); ok {
			return x.CreatePty
		}
	}
	return nil
}

func (x *ServerMessage) GetResizePty() *AgentResizePtyRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ResizePty); ok {
			return x.ResizePty
		}
	}
	return nil
}

func (x *ServerMessage) GetKillPty() *AgentKillPtyRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_KillPty); ok {
			return x.KillPty
		}
	}
	return nil
}

func (x *ServerMessage) GetPtyInput() *AgentPtyInput {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_PtyInput); ok {
			return x.PtyInput
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_HandshakeAck struct {
	// Handshake acknowledgment
	HandshakeAck *ServerHandshakeAck `protobuf:"bytes,1,opt,name=handshake_ack,json=handshakeAck,proto3,oneof"`
}

type ServerMessage_HeartbeatAck struct {
	// Heartbeat acknowledgment
	HeartbeatAck *ServerHeartbeatAck `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ServerMessage_RunCommand struct {
	// Run command request
	RunCommand *AgentRunCommandRequest `protobuf:"bytes,3,opt,name=run_command,json=runCommand,proto3,oneof"`
}

type ServerMessage_KillProcess struct {
	// Kill process request
	KillProcess *AgentKillProcessRequest `protobuf:"bytes,4,opt,name=kill_process,json=killProcess,proto3,oneof"`
}

type ServerMessage_CreatePty struct {
	// Create PTY request
	CreatePty *AgentCreatePtyRequest `protobuf:"bytes,5,opt,name=create_pty,json=createPty,proto3,oneof"`
}

type ServerMessage_ResizePty struct {
	// Resize PTY request
	ResizePty *AgentResizePtyRequest `protobuf:"bytes,6,opt,name=resize_pty,json=resizePty,proto3,oneof"`
}

type ServerMessage_KillPty struct {
	// Kill PTY request
	KillPty *AgentKillPtyRequest `protobuf:"bytes,7,opt,name=kill_pty,json=killPty,proto3,oneof"`
}

type ServerMessage_PtyInput struct {
	// PTY input
	PtyInput *AgentPtyInput `protobuf:"bytes,8,opt,name=pty_input,json=ptyInput,proto3,oneof"`
}

func (*ServerMessage_HandshakeAck) isServerMessage_Message() {}

func (*ServerMessage_HeartbeatAck) isServerMessage_Message() {}

func (*ServerMessage_RunCommand) isServerMessage_Message() {}

func (*ServerMessage_KillProcess) isServerMessage_Message() {}

func (*ServerMessage_CreatePty) isServerMessage_Message() {}

func (*ServerMessage_ResizePty) isServerMessage_Message() {}

func (*ServerMessage_KillPty) isServerMessage_Message() {}

func (*ServerMessage_PtyInput) isServerMessage_Message() {}

// Server handshake acknowledgment
type ServerHandshakeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHandshakeAck) Reset() {
	*x = ServerHandshakeAck{}
	mi := &file_workspace_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHandshakeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHandshakeAck) ProtoMessage() {}

func (x *ServerHandshakeAck) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHandshakeAck.ProtoReflect.Descriptor instead.
func (*ServerHandshakeAck) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ServerHandshakeAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerHandshakeAck) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Server heartbeat acknowledgment
type ServerHeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHeartbeatAck) Reset() {
	*x = ServerHeartbeatAck{}
	mi := &file_workspace_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHeartbeatAck) ProtoMessage() {}

func (x *ServerHeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHeartbeatAck.ProtoReflect.Descriptor instead.
func (*ServerHeartbeatAck) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ServerHeartbeatAck) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Run command request for agent
type AgentRunCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation ID for matching response
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Command to execute
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// Command arguments
	Args []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// Environment variables
	Env map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Working directory (optional)
	Cwd *string `protobuf:"bytes,5,opt,name=cwd,proto3,oneof" json:"cwd,omitempty"`
	// Timeout in milliseconds (0 = no timeout)
	TimeoutMs uint64 `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Whether to stream output
	Stream        bool `protobuf:"varint,7,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunCommandRequest) Reset() {
	*x = AgentRunCommandRequest{}
	mi := &file_workspace_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunCommandRequest) ProtoMessage() {}

func (x *AgentRunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunCommandRequest.ProtoReflect.Descriptor instead.
func (*AgentRunCommandRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *AgentRunCommandRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentRunCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *AgentRunCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AgentRunCommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *AgentRunCommandRequest) GetCwd() string {
	if x != nil && x.Cwd != nil {
		return *x.Cwd
	}
	return ""
}

func (x *AgentRunCommandRequest) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *AgentRunCommandRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

// Kill process request for agent
type AgentKillProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation ID
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Process ID
	Pid uint32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// Signal (default: SIGTERM = 15)
	Signal        int32 `protobuf:"varint,3,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentKillProcessRequest) Reset() {
	*x = AgentKillProcessRequest{}
	mi := &file_workspace_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentKillProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentKillProcessRequest) ProtoMessage() {}

func (x *AgentKillProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentKillProcessRequest.ProtoReflect.Descriptor instead.
func (*AgentKillProcessRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *AgentKillProcessRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentKillProcessRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AgentKillProcessRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

// Create PTY request for agent
type AgentCreatePtyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation ID
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// PTY ID (generated by server)
	PtyId string `protobuf:"bytes,2,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	// Columns
	Cols uint32 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	// Rows
	Rows uint32 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	// Shell
	Shell *string `protobuf:"bytes,5,opt,name=shell,proto3,oneof" json:"shell,omitempty"`
	// Environment variables
	Env           map[string]string `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCreatePtyRequest) Reset() {
	*x = AgentCreatePtyRequest{}
	mi := &file_workspace_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCreatePtyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCreatePtyRequest) ProtoMessage() {}

func (x *AgentCreatePtyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCreatePtyRequest.ProtoReflect.Descriptor instead.
func (*AgentCreatePtyRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *AgentCreatePtyRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentCreatePtyRequest) GetPtyId() string {
	if x != nil {
		return x.PtyId
	}
	return ""
}

func (x *AgentCreatePtyRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *AgentCreatePtyRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *AgentCreatePtyRequest) GetShell() string {
	if x != nil && x.Shell != nil {
		return *x.Shell
	}
	return ""
}

func (x *AgentCreatePtyRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// Resize PTY request for agent
type AgentResizePtyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation ID
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// PTY ID
	PtyId string `protobuf:"bytes,2,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	// New columns
	Cols uint32 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	// New rows
	Rows          uint32 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResizePtyRequest) Reset() {
	*x = AgentResizePtyRequest{}
	mi := &file_workspace_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResizePtyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResizePtyRequest) ProtoMessage() {}

func (x *AgentResizePtyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResizePtyRequest.ProtoReflect.Descriptor instead.
func (*AgentResizePtyRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *AgentResizePtyRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentResizePtyRequest) GetPtyId() string {
	if x != nil {
		return x.PtyId
	}
	return ""
}

func (x *AgentResizePtyRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *AgentResizePtyRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// Kill PTY request for agent
type AgentKillPtyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation ID
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// PTY ID
	PtyId         string `protobuf:"bytes,2,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentKillPtyRequest) Reset() {
	*x = AgentKillPtyRequest{}
	mi := &file_workspace_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentKillPtyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentKillPtyRequest) ProtoMessage() {}

func (x *AgentKillPtyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentKillPtyRequest.ProtoReflect.Descriptor instead.
func (*AgentKillPtyRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *AgentKillPtyRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentKillPtyRequest) GetPtyId() string {
	if x != nil {
		return x.PtyId
	}
	return ""
}

// PTY input from server to agent
type AgentPtyInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PTY ID
	PtyId string `protobuf:"bytes,1,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	// Input data
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPtyInput) Reset() {
	*x = AgentPtyInput{}
	mi := &file_workspace_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPtyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPtyInput) ProtoMessage() {}

func (x *AgentPtyInput) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPtyInput.ProtoReflect.Descriptor instead.
func (*AgentPtyInput) Descriptor() ([]byte, []int) {
	return file_workspace_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *AgentPtyInput) GetPtyId() string {
	if x != nil {
		return x.PtyId
	}
	return ""
}

func (x *AgentPtyInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_workspace_v1_agent_proto protoreflect.FileDescriptor

const file_workspace_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18workspace/v1/agent.proto\x12\fworkspace.v1\"\xa5\x02\n" +
	"\fAgentMessage\x12<\n" +
	"\thandshake\x18\x01 \x01(\v2\x1c.workspace.v1.AgentHandshakeH\x00R\thandshake\x12<\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1c.workspace.v1.AgentHeartbeatH\x00R\theartbeat\x12O\n" +
	"\x10command_response\x18\x03 \x01(\v2\".workspace.v1.AgentCommandResponseH\x00R\x0fcommandResponse\x12=\n" +
	"\n" +
	"pty_output\x18\x04 \x01(\v2\x1c.workspace.v1.AgentPtyOutputH\x00R\tptyOutputB\t\n" +
	"\amessage\"I\n" +
	"\x0eAgentHandshake\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\".\n" +
	"\x0eAgentHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"\xbf\x01\n" +
	"\x14AgentCommandResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12=\n" +
	"\asuccess\x18\x02 \x01(\v2!.workspace.v1.AgentCommandSuccessH\x00R\asuccess\x127\n" +
	"\x05error\x18\x03 \x01(\v2\x1f.workspace.v1.AgentCommandErrorH\x00R\x05errorB\b\n" +
	"\x06result\"b\n" +
	"\x13AgentCommandSuccess\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\"A\n" +
	"\x11AgentCommandError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x0eAgentPtyOutput\x12\x15\n" +
	"\x06pty_id\x18\x01 \x01(\tR\x05ptyId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xc9\x04\n" +
	"\rServerMessage\x12G\n" +
	"\rhandshake_ack\x18\x01 \x01(\v2 .workspace.v1.ServerHandshakeAckH\x00R\fhandshakeAck\x12G\n" +
	"\rheartbeat_ack\x18\x02 \x01(\v2 .workspace.v1.ServerHeartbeatAckH\x00R\fheartbeatAck\x12G\n" +
	"\vrun_command\x18\x03 \x01(\v2$.workspace.v1.AgentRunCommandRequestH\x00R\n" +
	"runCommand\x12J\n" +
	"\fkill_process\x18\x04 \x01(\v2%.workspace.v1.AgentKillProcessRequestH\x00R\vkillProcess\x12D\n" +
	"\n" +
	"create_pty\x18\x05 \x01(\v2#.workspace.v1.AgentCreatePtyRequestH\x00R\tcreatePty\x12D\n" +
	"\n" +
	"resize_pty\x18\x06 \x01(\v2#.workspace.v1.AgentResizePtyRequestH\x00R\tresizePty\x12>\n" +
	"\bkill_pty\x18\a \x01(\v2!.workspace.v1.AgentKillPtyRequestH\x00R\akillPty\x12:\n" +
	"\tpty_input\x18\b \x01(\v2\x1b.workspace.v1.AgentPtyInputH\x00R\bptyInputB\t\n" +
	"\amessage\"S\n" +
	"\x12ServerHandshakeAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"2\n" +
	"\x12ServerHeartbeatAck\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"\xbc\x02\n" +
	"\x16AgentRunCommandRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12?\n" +
	"\x03env\x18\x04 \x03(\v2-.workspace.v1.AgentRunCommandRequest.EnvEntryR\x03env\x12\x15\n" +
	"\x03cwd\x18\x05 \x01(\tH\x00R\x03cwd\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x04R\ttimeoutMs\x12\x16\n" +
	"\x06stream\x18\a \x01(\bR\x06stream\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_cwd\"j\n" +
	"\x17AgentKillProcessRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\x05R\x06signal\"\x9a\x02\n" +
	"\x15AgentCreatePtyRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x15\n" +
	"\x06pty_id\x18\x02 \x01(\tR\x05ptyId\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\x12\x19\n" +
	"\x05shell\x18\x05 \x01(\tH\x00R\x05shell\x88\x01\x01\x12>\n" +
	"\x03env\x18\x06 \x03(\v2,.workspace.v1.AgentCreatePtyRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_shell\"}\n" +
	"\x15AgentResizePtyRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x15\n" +
	"\x06pty_id\x18\x02 \x01(\tR\x05ptyId\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\"S\n" +
	"\x13AgentKillPtyRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x15\n" +
	"\x06pty_id\x18\x02 \x01(\tR\x05ptyId\":\n" +
	"\rAgentPtyInput\x12\x15\n" +
	"\x06pty_id\x18\x01 \x01(\tR\x05ptyId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2V\n" +
	"\fAgentService\x12F\n" +
	"\aConnect\x12\x1a.workspace.v1.AgentMessage\x1a\x1b.workspace.v1.ServerMessage(\x010\x01B6Z4github.com/OpenElevo/ElevoSandbox/proto/workspace/v1b\x06proto3"

var (
	file_workspace_v1_agent_proto_rawDescOnce sync.Once
	file_workspace_v1_agent_proto_rawDescData []byte
)

func file_workspace_v1_agent_proto_rawDescGZIP() []byte {
	file_workspace_v1_agent_proto_rawDescOnce.Do(func() {
		file_workspace_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_agent_proto_rawDesc), len(file_workspace_v1_agent_proto_rawDesc)))
	})
	return file_workspace_v1_agent_proto_rawDescData
}

var file_workspace_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_workspace_v1_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),            // 0: workspace.v1.AgentMessage
	(*AgentHandshake)(nil),          // 1: workspace.v1.AgentHandshake
	(*AgentHeartbeat)(nil),          // 2: workspace.v1.AgentHeartbeat
	(*AgentCommandResponse)(nil),    // 3: workspace.v1.AgentCommandResponse
	(*AgentCommandSuccess)(nil),     // 4: workspace.v1.AgentCommandSuccess
	(*AgentCommandError)(nil),       // 5: workspace.v1.AgentCommandError
	(*AgentPtyOutput)(nil),          // 6: workspace.v1.AgentPtyOutput
	(*ServerMessage)(nil),           // 7: workspace.v1.ServerMessage
	(*ServerHandshakeAck)(nil),      // 8: workspace.v1.ServerHandshakeAck
	(*ServerHeartbeatAck)(nil),      // 9: workspace.v1.ServerHeartbeatAck
	(*AgentRunCommandRequest)(nil),  // 10: workspace.v1.AgentRunCommandRequest
	(*AgentKillProcessRequest)(nil), // 11: workspace.v1.AgentKillProcessRequest
	(*AgentCreatePtyRequest)(nil),   // 12: workspace.v1.AgentCreatePtyRequest
	(*AgentResizePtyRequest)(nil),   // 13: workspace.v1.AgentResizePtyRequest
	(*AgentKillPtyRequest)(nil),     // 14: workspace.v1.AgentKillPtyRequest
	(*AgentPtyInput)(nil),           // 15: workspace.v1.AgentPtyInput
	nil,                             // 16: workspace.v1.AgentRunCommandRequest.EnvEntry
	nil,                             // 17: workspace.v1.AgentCreatePtyRequest.EnvEntry
}
var file_workspace_v1_agent_proto_depIdxs = []int32{
	1,  // 0: workspace.v1.AgentMessage.handshake:type_name -> workspace.v1.AgentHandshake
	2,  // 1: workspace.v1.AgentMessage.heartbeat:type_name -> workspace.v1.AgentHeartbeat
	3,  // 2: workspace.v1.AgentMessage.command_response:type_name -> workspace.v1.AgentCommandResponse
	6,  // 3: workspace.v1.AgentMessage.pty_output:type_name -> workspace.v1.AgentPtyOutput
	4,  // 4: workspace.v1.AgentCommandResponse.success:type_name -> workspace.v1.AgentCommandSuccess
	5,  // 5: workspace.v1.AgentCommandResponse.error:type_name -> workspace.v1.AgentCommandError
	8,  // 6: workspace.v1.ServerMessage.handshake_ack:type_name -> workspace.v1.ServerHandshakeAck
	9,  // 7: workspace.v1.ServerMessage.heartbeat_ack:type_name -> workspace.v1.ServerHeartbeatAck
	10, // 8: workspace.v1.ServerMessage.run_command:type_name -> workspace.v1.AgentRunCommandRequest
	11, // 9: workspace.v1.ServerMessage.kill_process:type_name -> workspace.v1.AgentKillProcessRequest
	12, // 10: workspace.v1.ServerMessage.create_pty:type_name -> workspace.v1.AgentCreatePtyRequest
	13, // 11: workspace.v1.ServerMessage.resize_pty:type_name -> workspace.v1.AgentResizePtyRequest
	14, // 12: workspace.v1.ServerMessage.kill_pty:type_name -> workspace.v1.AgentKillPtyRequest
	15, // 13: workspace.v1.ServerMessage.pty_input:type_name -> workspace.v1.AgentPtyInput
	16, // 14: workspace.v1.AgentRunCommandRequest.env:type_name -> workspace.v1.AgentRunCommandRequest.EnvEntry
	17, // 15: workspace.v1.AgentCreatePtyRequest.env:type_name -> workspace.v1.AgentCreatePtyRequest.EnvEntry
	0,  // 16: workspace.v1.AgentService.Connect:input_type -> workspace.v1.AgentMessage
	7,  // 17: workspace.v1.AgentService.Connect:output_type -> workspace.v1.ServerMessage
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_workspace_v1_agent_proto_init() }
func file_workspace_v1_agent_proto_init() {
	if File_workspace_v1_agent_proto != nil {
		return
	}
	file_workspace_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Handshake)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_CommandResponse)(nil),
		(*AgentMessage_PtyOutput)(nil),
	}
	file_workspace_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentCommandResponse_Success)(nil),
		(*AgentCommandResponse_Error)(nil),
	}
	file_workspace_v1_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_HandshakeAck)(nil),
		(*ServerMessage_HeartbeatAck)(nil),
		(*ServerMessage_RunCommand)(nil),
		(*ServerMessage_KillProcess)(nil),
		(*ServerMessage_CreatePty)(nil),
		(*ServerMessage_ResizePty)(nil),
		(*ServerMessage_KillPty)(nil),
		(*ServerMessage_PtyInput)(nil),
	}
	file_workspace_v1_agent_proto_msgTypes[8].OneofWrappers = []any{}
	file_workspace_v1_agent_proto_msgTypes[10].OneofWrappers = []any{}
	file_workspace_v1_agent_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_agent_proto_rawDesc), len(file_workspace_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_agent_proto_goTypes,
		DependencyIndexes: file_workspace_v1_agent_proto_depIdxs,
		MessageInfos:      file_workspace_v1_agent_proto_msgTypes,
	}.Build()
	File_workspace_v1_agent_proto = out.File
	file_workspace_v1_agent_proto_goTypes = nil
	file_workspace_v1_agent_proto_depIdxs = nil
}
