// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: workspace/v1/client_storage.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientStorageService_Connect_FullMethodName         = "/workspace.v1.ClientStorageService/Connect"
	ClientStorageService_ReadFileStream_FullMethodName  = "/workspace.v1.ClientStorageService/ReadFileStream"
	ClientStorageService_WriteFileStream_FullMethodName = "/workspace.v1.ClientStorageService/WriteFileStream"
)

// ClientStorageServiceClient is the client API for ClientStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientStorageService — Client reverse-stream connection service.
// Client connects to Server and serves file operations on its local directory.
type ClientStorageServiceClient interface {
	// Control stream: bidirectional, carries metadata operations and heartbeat
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerStorageMessage], error)
	// Data stream: Client reads local file and streams to Server (client-streaming)
	// Data direction: Client -> Server (file content from Client local disk to Server)
	ReadFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReadFileStreamRequest, ReadFileStreamResponse], error)
	// Data stream: Server streams data to Client for writing (server-streaming)
	// Data direction: Server -> Client (file content from Server to Client local disk)
	WriteFileStream(ctx context.Context, in *WriteFileStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WriteFileStreamResponse], error)
}

type clientStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientStorageServiceClient(cc grpc.ClientConnInterface) ClientStorageServiceClient {
	return &clientStorageServiceClient{cc}
}

func (c *clientStorageServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerStorageMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientStorageService_ServiceDesc.Streams[0], ClientStorageService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerStorageMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientStorageService_ConnectClient = grpc.BidiStreamingClient[ClientMessage, ServerStorageMessage]

func (c *clientStorageServiceClient) ReadFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReadFileStreamRequest, ReadFileStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientStorageService_ServiceDesc.Streams[1], ClientStorageService_ReadFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadFileStreamRequest, ReadFileStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientStorageService_ReadFileStreamClient = grpc.ClientStreamingClient[ReadFileStreamRequest, ReadFileStreamResponse]

func (c *clientStorageServiceClient) WriteFileStream(ctx context.Context, in *WriteFileStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WriteFileStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientStorageService_ServiceDesc.Streams[2], ClientStorageService_WriteFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFileStreamRequest, WriteFileStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientStorageService_WriteFileStreamClient = grpc.ServerStreamingClient[WriteFileStreamResponse]

// ClientStorageServiceServer is the server API for ClientStorageService service.
// All implementations must embed UnimplementedClientStorageServiceServer
// for forward compatibility.
//
// ClientStorageService — Client reverse-stream connection service.
// Client connects to Server and serves file operations on its local directory.
type ClientStorageServiceServer interface {
	// Control stream: bidirectional, carries metadata operations and heartbeat
	Connect(grpc.BidiStreamingServer[ClientMessage, ServerStorageMessage]) error
	// Data stream: Client reads local file and streams to Server (client-streaming)
	// Data direction: Client -> Server (file content from Client local disk to Server)
	ReadFileStream(grpc.ClientStreamingServer[ReadFileStreamRequest, ReadFileStreamResponse]) error
	// Data stream: Server streams data to Client for writing (server-streaming)
	// Data direction: Server -> Client (file content from Server to Client local disk)
	WriteFileStream(*WriteFileStreamRequest, grpc.ServerStreamingServer[WriteFileStreamResponse]) error
	mustEmbedUnimplementedClientStorageServiceServer()
}

// UnimplementedClientStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientStorageServiceServer struct{}

func (UnimplementedClientStorageServiceServer) Connect(grpc.BidiStreamingServer[ClientMessage, ServerStorageMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedClientStorageServiceServer) ReadFileStream(grpc.ClientStreamingServer[ReadFileStreamRequest, ReadFileStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadFileStream not implemented")
}
func (UnimplementedClientStorageServiceServer) WriteFileStream(*WriteFileStreamRequest, grpc.ServerStreamingServer[WriteFileStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteFileStream not implemented")
}
func (UnimplementedClientStorageServiceServer) mustEmbedUnimplementedClientStorageServiceServer() {}
func (UnimplementedClientStorageServiceServer) testEmbeddedByValue()                              {}

// UnsafeClientStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientStorageServiceServer will
// result in compilation errors.
type UnsafeClientStorageServiceServer interface {
	mustEmbedUnimplementedClientStorageServiceServer()
}

func RegisterClientStorageServiceServer(s grpc.ServiceRegistrar, srv ClientStorageServiceServer) {
	// If the following call panics, it indicates UnimplementedClientStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientStorageService_ServiceDesc, srv)
}

func _ClientStorageService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientStorageServiceServer).Connect(&grpc.GenericServerStream[ClientMessage, ServerStorageMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientStorageService_ConnectServer = grpc.BidiStreamingServer[ClientMessage, ServerStorageMessage]

func _ClientStorageService_ReadFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientStorageServiceServer).ReadFileStream(&grpc.GenericServerStream[ReadFileStreamRequest, ReadFileStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientStorageService_ReadFileStreamServer = grpc.ClientStreamingServer[ReadFileStreamRequest, ReadFileStreamResponse]

func _ClientStorageService_WriteFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WriteFileStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientStorageServiceServer).WriteFileStream(m, &grpc.GenericServerStream[WriteFileStreamRequest, WriteFileStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientStorageService_WriteFileStreamServer = grpc.ServerStreamingServer[WriteFileStreamResponse]

// ClientStorageService_ServiceDesc is the grpc.ServiceDesc for ClientStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workspace.v1.ClientStorageService",
	HandlerType: (*ClientStorageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ClientStorageService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadFileStream",
			Handler:       _ClientStorageService_ReadFileStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WriteFileStream",
			Handler:       _ClientStorageService_WriteFileStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workspace/v1/client_storage.proto",
}
