// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workspace/v1/process.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Run command request
type RunCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox ID
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Command to execute
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// Command arguments
	Args []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// Environment variables
	Env map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Working directory (optional)
	Cwd *string `protobuf:"bytes,5,opt,name=cwd,proto3,oneof" json:"cwd,omitempty"`
	// Timeout in milliseconds (optional, 0 = no timeout)
	TimeoutMs     *uint64 `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3,oneof" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	mi := &file_workspace_v1_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_process_proto_rawDescGZIP(), []int{0}
}

func (x *RunCommandRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RunCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunCommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunCommandRequest) GetCwd() string {
	if x != nil && x.Cwd != nil {
		return *x.Cwd
	}
	return ""
}

func (x *RunCommandRequest) GetTimeoutMs() uint64 {
	if x != nil && x.TimeoutMs != nil {
		return *x.TimeoutMs
	}
	return 0
}

// Run command response
type RunCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *CommandResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandResponse) Reset() {
	*x = RunCommandResponse{}
	mi := &file_workspace_v1_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResponse) ProtoMessage() {}

func (x *RunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResponse.ProtoReflect.Descriptor instead.
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_process_proto_rawDescGZIP(), []int{1}
}

func (x *RunCommandResponse) GetResult() *CommandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// Command result
type CommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exit code
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Standard output
	Stdout string `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Standard error
	Stderr        string `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_workspace_v1_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_workspace_v1_process_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

// Process event for streaming
type ProcessEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ProcessEvent_Stdout
	//	*ProcessEvent_Stderr
	//	*ProcessEvent_Exit
	//	*ProcessEvent_Error
	Event         isProcessEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent) Reset() {
	*x = ProcessEvent{}
	mi := &file_workspace_v1_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent) ProtoMessage() {}

func (x *ProcessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent) Descriptor() ([]byte, []int) {
	return file_workspace_v1_process_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessEvent) GetEvent() isProcessEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ProcessEvent) GetStdout() *StdoutEvent {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ProcessEvent) GetStderr() *StderrEvent {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ProcessEvent) GetExit() *ExitEvent {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *ProcessEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isProcessEvent_Event interface {
	isProcessEvent_Event()
}

type ProcessEvent_Stdout struct {
	Stdout *StdoutEvent `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ProcessEvent_Stderr struct {
	Stderr *StderrEvent `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ProcessEvent_Exit struct {
	Exit *ExitEvent `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

type ProcessEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ProcessEvent_Stdout) isProcessEvent_Event() {}

func (*ProcessEvent_Stderr) isProcessEvent_Event() {}

func (*ProcessEvent_Exit) isProcessEvent_Event() {}

func (*ProcessEvent_Error) isProcessEvent_Event() {}

// Stdout event
type StdoutEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdoutEvent) Reset() {
	*x = StdoutEvent{}
	mi := &file_workspace_v1_process_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdoutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdoutEvent) ProtoMessage() {}

func (x *StdoutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_process_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdoutEvent.ProtoReflect.Descriptor instead.
func (*StdoutEvent) Descriptor() ([]byte, []int) {
	return file_workspace_v1_process_proto_rawDescGZIP(), []int{4}
}

func (x *StdoutEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Stderr event
type StderrEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StderrEvent) Reset() {
	*x = StderrEvent{}
	mi := &file_workspace_v1_process_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StderrEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StderrEvent) ProtoMessage() {}

func (x *StderrEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_process_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StderrEvent.ProtoReflect.Descriptor instead.
func (*StderrEvent) Descriptor() ([]byte, []int) {
	return file_workspace_v1_process_proto_rawDescGZIP(), []int{5}
}

func (x *StderrEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Exit event
type ExitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitEvent) Reset() {
	*x = ExitEvent{}
	mi := &file_workspace_v1_process_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitEvent) ProtoMessage() {}

func (x *ExitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_process_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitEvent.ProtoReflect.Descriptor instead.
func (*ExitEvent) Descriptor() ([]byte, []int) {
	return file_workspace_v1_process_proto_rawDescGZIP(), []int{6}
}

func (x *ExitEvent) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// Error event
type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_workspace_v1_process_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_process_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_workspace_v1_process_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Kill process request
type KillProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox ID
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Process ID to kill
	Pid uint32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// Signal to send (default: SIGTERM = 15)
	Signal        *int32 `protobuf:"varint,3,opt,name=signal,proto3,oneof" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessRequest) Reset() {
	*x = KillProcessRequest{}
	mi := &file_workspace_v1_process_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessRequest) ProtoMessage() {}

func (x *KillProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_process_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessRequest.ProtoReflect.Descriptor instead.
func (*KillProcessRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_process_proto_rawDescGZIP(), []int{8}
}

func (x *KillProcessRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *KillProcessRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *KillProcessRequest) GetSignal() int32 {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	return 0
}

// Kill process response
type KillProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessResponse) Reset() {
	*x = KillProcessResponse{}
	mi := &file_workspace_v1_process_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessResponse) ProtoMessage() {}

func (x *KillProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_process_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessResponse.ProtoReflect.Descriptor instead.
func (*KillProcessResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_process_proto_rawDescGZIP(), []int{9}
}

func (x *KillProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_workspace_v1_process_proto protoreflect.FileDescriptor

const file_workspace_v1_process_proto_rawDesc = "" +
	"\n" +
	"\x1aworkspace/v1/process.proto\x12\fworkspace.v1\"\xa6\x02\n" +
	"\x11RunCommandRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12:\n" +
	"\x03env\x18\x04 \x03(\v2(.workspace.v1.RunCommandRequest.EnvEntryR\x03env\x12\x15\n" +
	"\x03cwd\x18\x05 \x01(\tH\x00R\x03cwd\x88\x01\x01\x12\"\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x04H\x01R\ttimeoutMs\x88\x01\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_cwdB\r\n" +
	"\v_timeout_ms\"I\n" +
	"\x12RunCommandResponse\x123\n" +
	"\x06result\x18\x01 \x01(\v2\x1b.workspace.v1.CommandResultR\x06result\"\\\n" +
	"\rCommandResult\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\"\xe2\x01\n" +
	"\fProcessEvent\x123\n" +
	"\x06stdout\x18\x01 \x01(\v2\x19.workspace.v1.StdoutEventH\x00R\x06stdout\x123\n" +
	"\x06stderr\x18\x02 \x01(\v2\x19.workspace.v1.StderrEventH\x00R\x06stderr\x12-\n" +
	"\x04exit\x18\x03 \x01(\v2\x17.workspace.v1.ExitEventH\x00R\x04exit\x120\n" +
	"\x05error\x18\x04 \x01(\v2\x18.workspace.v1.ErrorEventH\x00R\x05errorB\a\n" +
	"\x05event\"!\n" +
	"\vStdoutEvent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"!\n" +
	"\vStderrEvent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\x1f\n" +
	"\tExitEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"&\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"m\n" +
	"\x12KillProcessRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x1b\n" +
	"\x06signal\x18\x03 \x01(\x05H\x00R\x06signal\x88\x01\x01B\t\n" +
	"\a_signal\"/\n" +
	"\x13KillProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x88\x02\n" +
	"\x0eProcessService\x12O\n" +
	"\n" +
	"RunCommand\x12\x1f.workspace.v1.RunCommandRequest\x1a .workspace.v1.RunCommandResponse\x12Q\n" +
	"\x10RunCommandStream\x12\x1f.workspace.v1.RunCommandRequest\x1a\x1a.workspace.v1.ProcessEvent0\x01\x12R\n" +
	"\vKillProcess\x12 .workspace.v1.KillProcessRequest\x1a!.workspace.v1.KillProcessResponseB6Z4github.com/OpenElevo/ElevoSandbox/proto/workspace/v1b\x06proto3"

var (
	file_workspace_v1_process_proto_rawDescOnce sync.Once
	file_workspace_v1_process_proto_rawDescData []byte
)

func file_workspace_v1_process_proto_rawDescGZIP() []byte {
	file_workspace_v1_process_proto_rawDescOnce.Do(func() {
		file_workspace_v1_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_process_proto_rawDesc), len(file_workspace_v1_process_proto_rawDesc)))
	})
	return file_workspace_v1_process_proto_rawDescData
}

var file_workspace_v1_process_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_workspace_v1_process_proto_goTypes = []any{
	(*RunCommandRequest)(nil),   // 0: workspace.v1.RunCommandRequest
	(*RunCommandResponse)(nil),  // 1: workspace.v1.RunCommandResponse
	(*CommandResult)(nil),       // 2: workspace.v1.CommandResult
	(*ProcessEvent)(nil),        // 3: workspace.v1.ProcessEvent
	(*StdoutEvent)(nil),         // 4: workspace.v1.StdoutEvent
	(*StderrEvent)(nil),         // 5: workspace.v1.StderrEvent
	(*ExitEvent)(nil),           // 6: workspace.v1.ExitEvent
	(*ErrorEvent)(nil),          // 7: workspace.v1.ErrorEvent
	(*KillProcessRequest)(nil),  // 8: workspace.v1.KillProcessRequest
	(*KillProcessResponse)(nil), // 9: workspace.v1.KillProcessResponse
	nil,                         // 10: workspace.v1.RunCommandRequest.EnvEntry
}
var file_workspace_v1_process_proto_depIdxs = []int32{
	10, // 0: workspace.v1.RunCommandRequest.env:type_name -> workspace.v1.RunCommandRequest.EnvEntry
	2,  // 1: workspace.v1.RunCommandResponse.result:type_name -> workspace.v1.CommandResult
	4,  // 2: workspace.v1.ProcessEvent.stdout:type_name -> workspace.v1.StdoutEvent
	5,  // 3: workspace.v1.ProcessEvent.stderr:type_name -> workspace.v1.StderrEvent
	6,  // 4: workspace.v1.ProcessEvent.exit:type_name -> workspace.v1.ExitEvent
	7,  // 5: workspace.v1.ProcessEvent.error:type_name -> workspace.v1.ErrorEvent
	0,  // 6: workspace.v1.ProcessService.RunCommand:input_type -> workspace.v1.RunCommandRequest
	0,  // 7: workspace.v1.ProcessService.RunCommandStream:input_type -> workspace.v1.RunCommandRequest
	8,  // 8: workspace.v1.ProcessService.KillProcess:input_type -> workspace.v1.KillProcessRequest
	1,  // 9: workspace.v1.ProcessService.RunCommand:output_type -> workspace.v1.RunCommandResponse
	3,  // 10: workspace.v1.ProcessService.RunCommandStream:output_type -> workspace.v1.ProcessEvent
	9,  // 11: workspace.v1.ProcessService.KillProcess:output_type -> workspace.v1.KillProcessResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_workspace_v1_process_proto_init() }
func file_workspace_v1_process_proto_init() {
	if File_workspace_v1_process_proto != nil {
		return
	}
	file_workspace_v1_process_proto_msgTypes[0].OneofWrappers = []any{}
	file_workspace_v1_process_proto_msgTypes[3].OneofWrappers = []any{
		(*ProcessEvent_Stdout)(nil),
		(*ProcessEvent_Stderr)(nil),
		(*ProcessEvent_Exit)(nil),
		(*ProcessEvent_Error)(nil),
	}
	file_workspace_v1_process_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_process_proto_rawDesc), len(file_workspace_v1_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_process_proto_goTypes,
		DependencyIndexes: file_workspace_v1_process_proto_depIdxs,
		MessageInfos:      file_workspace_v1_process_proto_msgTypes,
	}.Build()
	File_workspace_v1_process_proto = out.File
	file_workspace_v1_process_proto_goTypes = nil
	file_workspace_v1_process_proto_depIdxs = nil
}
