// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workspace/v1/pty.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create PTY request
type CreatePtyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox ID
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Terminal columns (default: 80)
	Cols *uint32 `protobuf:"varint,2,opt,name=cols,proto3,oneof" json:"cols,omitempty"`
	// Terminal rows (default: 24)
	Rows *uint32 `protobuf:"varint,3,opt,name=rows,proto3,oneof" json:"rows,omitempty"`
	// Shell to use (optional, defaults to /bin/bash)
	Shell *string `protobuf:"bytes,4,opt,name=shell,proto3,oneof" json:"shell,omitempty"`
	// Environment variables
	Env           map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePtyRequest) Reset() {
	*x = CreatePtyRequest{}
	mi := &file_workspace_v1_pty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePtyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePtyRequest) ProtoMessage() {}

func (x *CreatePtyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePtyRequest.ProtoReflect.Descriptor instead.
func (*CreatePtyRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePtyRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreatePtyRequest) GetCols() uint32 {
	if x != nil && x.Cols != nil {
		return *x.Cols
	}
	return 0
}

func (x *CreatePtyRequest) GetRows() uint32 {
	if x != nil && x.Rows != nil {
		return *x.Rows
	}
	return 0
}

func (x *CreatePtyRequest) GetShell() string {
	if x != nil && x.Shell != nil {
		return *x.Shell
	}
	return ""
}

func (x *CreatePtyRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// Create PTY response
type CreatePtyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pty           *PtyInfo               `protobuf:"bytes,1,opt,name=pty,proto3" json:"pty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePtyResponse) Reset() {
	*x = CreatePtyResponse{}
	mi := &file_workspace_v1_pty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePtyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePtyResponse) ProtoMessage() {}

func (x *CreatePtyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePtyResponse.ProtoReflect.Descriptor instead.
func (*CreatePtyResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePtyResponse) GetPty() *PtyInfo {
	if x != nil {
		return x.Pty
	}
	return nil
}

// PTY information
type PtyInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PTY ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Sandbox ID
	SandboxId string `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Terminal columns
	Cols uint32 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	// Terminal rows
	Rows          uint32 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyInfo) Reset() {
	*x = PtyInfo{}
	mi := &file_workspace_v1_pty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyInfo) ProtoMessage() {}

func (x *PtyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyInfo.ProtoReflect.Descriptor instead.
func (*PtyInfo) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{2}
}

func (x *PtyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PtyInfo) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *PtyInfo) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PtyInfo) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// Resize PTY request
type ResizePtyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox ID
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// PTY ID
	PtyId string `protobuf:"bytes,2,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	// New columns
	Cols uint32 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	// New rows
	Rows          uint32 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizePtyRequest) Reset() {
	*x = ResizePtyRequest{}
	mi := &file_workspace_v1_pty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizePtyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizePtyRequest) ProtoMessage() {}

func (x *ResizePtyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizePtyRequest.ProtoReflect.Descriptor instead.
func (*ResizePtyRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{3}
}

func (x *ResizePtyRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ResizePtyRequest) GetPtyId() string {
	if x != nil {
		return x.PtyId
	}
	return ""
}

func (x *ResizePtyRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ResizePtyRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// Resize PTY response
type ResizePtyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizePtyResponse) Reset() {
	*x = ResizePtyResponse{}
	mi := &file_workspace_v1_pty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizePtyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizePtyResponse) ProtoMessage() {}

func (x *ResizePtyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizePtyResponse.ProtoReflect.Descriptor instead.
func (*ResizePtyResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{4}
}

func (x *ResizePtyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Kill PTY request
type KillPtyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox ID
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// PTY ID
	PtyId         string `protobuf:"bytes,2,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillPtyRequest) Reset() {
	*x = KillPtyRequest{}
	mi := &file_workspace_v1_pty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillPtyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillPtyRequest) ProtoMessage() {}

func (x *KillPtyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillPtyRequest.ProtoReflect.Descriptor instead.
func (*KillPtyRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{5}
}

func (x *KillPtyRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *KillPtyRequest) GetPtyId() string {
	if x != nil {
		return x.PtyId
	}
	return ""
}

// Kill PTY response
type KillPtyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillPtyResponse) Reset() {
	*x = KillPtyResponse{}
	mi := &file_workspace_v1_pty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillPtyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillPtyResponse) ProtoMessage() {}

func (x *KillPtyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillPtyResponse.ProtoReflect.Descriptor instead.
func (*KillPtyResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{6}
}

func (x *KillPtyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PTY stream request (bidirectional streaming)
type PtyStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*PtyStreamRequest_Init
	//	*PtyStreamRequest_Input
	//	*PtyStreamRequest_Resize
	Request       isPtyStreamRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyStreamRequest) Reset() {
	*x = PtyStreamRequest{}
	mi := &file_workspace_v1_pty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyStreamRequest) ProtoMessage() {}

func (x *PtyStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyStreamRequest.ProtoReflect.Descriptor instead.
func (*PtyStreamRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{7}
}

func (x *PtyStreamRequest) GetRequest() isPtyStreamRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *PtyStreamRequest) GetInit() *PtyStreamInit {
	if x != nil {
		if x, ok := x.Request.(*PtyStreamRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *PtyStreamRequest) GetInput() []byte {
	if x != nil {
		if x, ok := x.Request.(*PtyStreamRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *PtyStreamRequest) GetResize() *PtyResizeEvent {
	if x != nil {
		if x, ok := x.Request.(*PtyStreamRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isPtyStreamRequest_Request interface {
	isPtyStreamRequest_Request()
}

type PtyStreamRequest_Init struct {
	// Initialize PTY stream connection
	Init *PtyStreamInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type PtyStreamRequest_Input struct {
	// Input data to send to PTY
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type PtyStreamRequest_Resize struct {
	// Resize event
	Resize *PtyResizeEvent `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*PtyStreamRequest_Init) isPtyStreamRequest_Request() {}

func (*PtyStreamRequest_Input) isPtyStreamRequest_Request() {}

func (*PtyStreamRequest_Resize) isPtyStreamRequest_Request() {}

// PTY stream initialization
type PtyStreamInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox ID
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// PTY ID
	PtyId         string `protobuf:"bytes,2,opt,name=pty_id,json=ptyId,proto3" json:"pty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyStreamInit) Reset() {
	*x = PtyStreamInit{}
	mi := &file_workspace_v1_pty_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyStreamInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyStreamInit) ProtoMessage() {}

func (x *PtyStreamInit) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyStreamInit.ProtoReflect.Descriptor instead.
func (*PtyStreamInit) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{8}
}

func (x *PtyStreamInit) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *PtyStreamInit) GetPtyId() string {
	if x != nil {
		return x.PtyId
	}
	return ""
}

// PTY resize event
type PtyResizeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New columns
	Cols uint32 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	// New rows
	Rows          uint32 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyResizeEvent) Reset() {
	*x = PtyResizeEvent{}
	mi := &file_workspace_v1_pty_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyResizeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyResizeEvent) ProtoMessage() {}

func (x *PtyResizeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyResizeEvent.ProtoReflect.Descriptor instead.
func (*PtyResizeEvent) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{9}
}

func (x *PtyResizeEvent) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PtyResizeEvent) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// PTY stream response (bidirectional streaming)
type PtyStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*PtyStreamResponse_Output
	//	*PtyStreamResponse_ExitCode
	//	*PtyStreamResponse_Error
	Response      isPtyStreamResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyStreamResponse) Reset() {
	*x = PtyStreamResponse{}
	mi := &file_workspace_v1_pty_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyStreamResponse) ProtoMessage() {}

func (x *PtyStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_pty_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyStreamResponse.ProtoReflect.Descriptor instead.
func (*PtyStreamResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_pty_proto_rawDescGZIP(), []int{10}
}

func (x *PtyStreamResponse) GetResponse() isPtyStreamResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PtyStreamResponse) GetOutput() []byte {
	if x != nil {
		if x, ok := x.Response.(*PtyStreamResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *PtyStreamResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Response.(*PtyStreamResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

func (x *PtyStreamResponse) GetError() string {
	if x != nil {
		if x, ok := x.Response.(*PtyStreamResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isPtyStreamResponse_Response interface {
	isPtyStreamResponse_Response()
}

type PtyStreamResponse_Output struct {
	// Output data from PTY
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type PtyStreamResponse_ExitCode struct {
	// PTY process exit code
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

type PtyStreamResponse_Error struct {
	// Error message
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*PtyStreamResponse_Output) isPtyStreamResponse_Response() {}

func (*PtyStreamResponse_ExitCode) isPtyStreamResponse_Response() {}

func (*PtyStreamResponse_Error) isPtyStreamResponse_Response() {}

var File_workspace_v1_pty_proto protoreflect.FileDescriptor

const file_workspace_v1_pty_proto_rawDesc = "" +
	"\n" +
	"\x16workspace/v1/pty.proto\x12\fworkspace.v1\"\x8d\x02\n" +
	"\x10CreatePtyRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x17\n" +
	"\x04cols\x18\x02 \x01(\rH\x00R\x04cols\x88\x01\x01\x12\x17\n" +
	"\x04rows\x18\x03 \x01(\rH\x01R\x04rows\x88\x01\x01\x12\x19\n" +
	"\x05shell\x18\x04 \x01(\tH\x02R\x05shell\x88\x01\x01\x129\n" +
	"\x03env\x18\x05 \x03(\v2'.workspace.v1.CreatePtyRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_colsB\a\n" +
	"\x05_rowsB\b\n" +
	"\x06_shell\"<\n" +
	"\x11CreatePtyResponse\x12'\n" +
	"\x03pty\x18\x01 \x01(\v2\x15.workspace.v1.PtyInfoR\x03pty\"`\n" +
	"\aPtyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\"p\n" +
	"\x10ResizePtyRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x15\n" +
	"\x06pty_id\x18\x02 \x01(\tR\x05ptyId\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\"-\n" +
	"\x11ResizePtyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x0eKillPtyRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x15\n" +
	"\x06pty_id\x18\x02 \x01(\tR\x05ptyId\"+\n" +
	"\x0fKillPtyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa0\x01\n" +
	"\x10PtyStreamRequest\x121\n" +
	"\x04init\x18\x01 \x01(\v2\x1b.workspace.v1.PtyStreamInitH\x00R\x04init\x12\x16\n" +
	"\x05input\x18\x02 \x01(\fH\x00R\x05input\x126\n" +
	"\x06resize\x18\x03 \x01(\v2\x1c.workspace.v1.PtyResizeEventH\x00R\x06resizeB\t\n" +
	"\arequest\"E\n" +
	"\rPtyStreamInit\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x15\n" +
	"\x06pty_id\x18\x02 \x01(\tR\x05ptyId\"8\n" +
	"\x0ePtyResizeEvent\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"p\n" +
	"\x11PtyStreamResponse\x12\x18\n" +
	"\x06output\x18\x01 \x01(\fH\x00R\x06output\x12\x1d\n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCode\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse2\xc2\x02\n" +
	"\n" +
	"PtyService\x12L\n" +
	"\tCreatePty\x12\x1e.workspace.v1.CreatePtyRequest\x1a\x1f.workspace.v1.CreatePtyResponse\x12L\n" +
	"\tResizePty\x12\x1e.workspace.v1.ResizePtyRequest\x1a\x1f.workspace.v1.ResizePtyResponse\x12F\n" +
	"\aKillPty\x12\x1c.workspace.v1.KillPtyRequest\x1a\x1d.workspace.v1.KillPtyResponse\x12P\n" +
	"\tPtyStream\x12\x1e.workspace.v1.PtyStreamRequest\x1a\x1f.workspace.v1.PtyStreamResponse(\x010\x01B6Z4github.com/OpenElevo/ElevoSandbox/proto/workspace/v1b\x06proto3"

var (
	file_workspace_v1_pty_proto_rawDescOnce sync.Once
	file_workspace_v1_pty_proto_rawDescData []byte
)

func file_workspace_v1_pty_proto_rawDescGZIP() []byte {
	file_workspace_v1_pty_proto_rawDescOnce.Do(func() {
		file_workspace_v1_pty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_pty_proto_rawDesc), len(file_workspace_v1_pty_proto_rawDesc)))
	})
	return file_workspace_v1_pty_proto_rawDescData
}

var file_workspace_v1_pty_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_workspace_v1_pty_proto_goTypes = []any{
	(*CreatePtyRequest)(nil),  // 0: workspace.v1.CreatePtyRequest
	(*CreatePtyResponse)(nil), // 1: workspace.v1.CreatePtyResponse
	(*PtyInfo)(nil),           // 2: workspace.v1.PtyInfo
	(*ResizePtyRequest)(nil),  // 3: workspace.v1.ResizePtyRequest
	(*ResizePtyResponse)(nil), // 4: workspace.v1.ResizePtyResponse
	(*KillPtyRequest)(nil),    // 5: workspace.v1.KillPtyRequest
	(*KillPtyResponse)(nil),   // 6: workspace.v1.KillPtyResponse
	(*PtyStreamRequest)(nil),  // 7: workspace.v1.PtyStreamRequest
	(*PtyStreamInit)(nil),     // 8: workspace.v1.PtyStreamInit
	(*PtyResizeEvent)(nil),    // 9: workspace.v1.PtyResizeEvent
	(*PtyStreamResponse)(nil), // 10: workspace.v1.PtyStreamResponse
	nil,                       // 11: workspace.v1.CreatePtyRequest.EnvEntry
}
var file_workspace_v1_pty_proto_depIdxs = []int32{
	11, // 0: workspace.v1.CreatePtyRequest.env:type_name -> workspace.v1.CreatePtyRequest.EnvEntry
	2,  // 1: workspace.v1.CreatePtyResponse.pty:type_name -> workspace.v1.PtyInfo
	8,  // 2: workspace.v1.PtyStreamRequest.init:type_name -> workspace.v1.PtyStreamInit
	9,  // 3: workspace.v1.PtyStreamRequest.resize:type_name -> workspace.v1.PtyResizeEvent
	0,  // 4: workspace.v1.PtyService.CreatePty:input_type -> workspace.v1.CreatePtyRequest
	3,  // 5: workspace.v1.PtyService.ResizePty:input_type -> workspace.v1.ResizePtyRequest
	5,  // 6: workspace.v1.PtyService.KillPty:input_type -> workspace.v1.KillPtyRequest
	7,  // 7: workspace.v1.PtyService.PtyStream:input_type -> workspace.v1.PtyStreamRequest
	1,  // 8: workspace.v1.PtyService.CreatePty:output_type -> workspace.v1.CreatePtyResponse
	4,  // 9: workspace.v1.PtyService.ResizePty:output_type -> workspace.v1.ResizePtyResponse
	6,  // 10: workspace.v1.PtyService.KillPty:output_type -> workspace.v1.KillPtyResponse
	10, // 11: workspace.v1.PtyService.PtyStream:output_type -> workspace.v1.PtyStreamResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_workspace_v1_pty_proto_init() }
func file_workspace_v1_pty_proto_init() {
	if File_workspace_v1_pty_proto != nil {
		return
	}
	file_workspace_v1_pty_proto_msgTypes[0].OneofWrappers = []any{}
	file_workspace_v1_pty_proto_msgTypes[7].OneofWrappers = []any{
		(*PtyStreamRequest_Init)(nil),
		(*PtyStreamRequest_Input)(nil),
		(*PtyStreamRequest_Resize)(nil),
	}
	file_workspace_v1_pty_proto_msgTypes[10].OneofWrappers = []any{
		(*PtyStreamResponse_Output)(nil),
		(*PtyStreamResponse_ExitCode)(nil),
		(*PtyStreamResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_pty_proto_rawDesc), len(file_workspace_v1_pty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_pty_proto_goTypes,
		DependencyIndexes: file_workspace_v1_pty_proto_depIdxs,
		MessageInfos:      file_workspace_v1_pty_proto_msgTypes,
	}.Build()
	File_workspace_v1_pty_proto = out.File
	file_workspace_v1_pty_proto_goTypes = nil
	file_workspace_v1_pty_proto_depIdxs = nil
}
