// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: workspace/v1/pty.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PtyService_CreatePty_FullMethodName = "/workspace.v1.PtyService/CreatePty"
	PtyService_ResizePty_FullMethodName = "/workspace.v1.PtyService/ResizePty"
	PtyService_KillPty_FullMethodName   = "/workspace.v1.PtyService/KillPty"
	PtyService_PtyStream_FullMethodName = "/workspace.v1.PtyService/PtyStream"
)

// PtyServiceClient is the client API for PtyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PTY service for interactive terminal sessions
type PtyServiceClient interface {
	// Create a new PTY
	CreatePty(ctx context.Context, in *CreatePtyRequest, opts ...grpc.CallOption) (*CreatePtyResponse, error)
	// Resize a PTY
	ResizePty(ctx context.Context, in *ResizePtyRequest, opts ...grpc.CallOption) (*ResizePtyResponse, error)
	// Kill a PTY
	KillPty(ctx context.Context, in *KillPtyRequest, opts ...grpc.CallOption) (*KillPtyResponse, error)
	// Bidirectional stream for PTY I/O
	PtyStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PtyStreamRequest, PtyStreamResponse], error)
}

type ptyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPtyServiceClient(cc grpc.ClientConnInterface) PtyServiceClient {
	return &ptyServiceClient{cc}
}

func (c *ptyServiceClient) CreatePty(ctx context.Context, in *CreatePtyRequest, opts ...grpc.CallOption) (*CreatePtyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePtyResponse)
	err := c.cc.Invoke(ctx, PtyService_CreatePty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ptyServiceClient) ResizePty(ctx context.Context, in *ResizePtyRequest, opts ...grpc.CallOption) (*ResizePtyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizePtyResponse)
	err := c.cc.Invoke(ctx, PtyService_ResizePty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ptyServiceClient) KillPty(ctx context.Context, in *KillPtyRequest, opts ...grpc.CallOption) (*KillPtyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillPtyResponse)
	err := c.cc.Invoke(ctx, PtyService_KillPty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ptyServiceClient) PtyStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PtyStreamRequest, PtyStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PtyService_ServiceDesc.Streams[0], PtyService_PtyStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PtyStreamRequest, PtyStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PtyService_PtyStreamClient = grpc.BidiStreamingClient[PtyStreamRequest, PtyStreamResponse]

// PtyServiceServer is the server API for PtyService service.
// All implementations must embed UnimplementedPtyServiceServer
// for forward compatibility.
//
// PTY service for interactive terminal sessions
type PtyServiceServer interface {
	// Create a new PTY
	CreatePty(context.Context, *CreatePtyRequest) (*CreatePtyResponse, error)
	// Resize a PTY
	ResizePty(context.Context, *ResizePtyRequest) (*ResizePtyResponse, error)
	// Kill a PTY
	KillPty(context.Context, *KillPtyRequest) (*KillPtyResponse, error)
	// Bidirectional stream for PTY I/O
	PtyStream(grpc.BidiStreamingServer[PtyStreamRequest, PtyStreamResponse]) error
	mustEmbedUnimplementedPtyServiceServer()
}

// UnimplementedPtyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPtyServiceServer struct{}

func (UnimplementedPtyServiceServer) CreatePty(context.Context, *CreatePtyRequest) (*CreatePtyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePty not implemented")
}
func (UnimplementedPtyServiceServer) ResizePty(context.Context, *ResizePtyRequest) (*ResizePtyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizePty not implemented")
}
func (UnimplementedPtyServiceServer) KillPty(context.Context, *KillPtyRequest) (*KillPtyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillPty not implemented")
}
func (UnimplementedPtyServiceServer) PtyStream(grpc.BidiStreamingServer[PtyStreamRequest, PtyStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method PtyStream not implemented")
}
func (UnimplementedPtyServiceServer) mustEmbedUnimplementedPtyServiceServer() {}
func (UnimplementedPtyServiceServer) testEmbeddedByValue()                    {}

// UnsafePtyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PtyServiceServer will
// result in compilation errors.
type UnsafePtyServiceServer interface {
	mustEmbedUnimplementedPtyServiceServer()
}

func RegisterPtyServiceServer(s grpc.ServiceRegistrar, srv PtyServiceServer) {
	// If the following call panics, it indicates UnimplementedPtyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PtyService_ServiceDesc, srv)
}

func _PtyService_CreatePty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePtyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtyServiceServer).CreatePty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PtyService_CreatePty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtyServiceServer).CreatePty(ctx, req.(*CreatePtyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PtyService_ResizePty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizePtyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtyServiceServer).ResizePty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PtyService_ResizePty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtyServiceServer).ResizePty(ctx, req.(*ResizePtyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PtyService_KillPty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillPtyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtyServiceServer).KillPty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PtyService_KillPty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtyServiceServer).KillPty(ctx, req.(*KillPtyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PtyService_PtyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PtyServiceServer).PtyStream(&grpc.GenericServerStream[PtyStreamRequest, PtyStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PtyService_PtyStreamServer = grpc.BidiStreamingServer[PtyStreamRequest, PtyStreamResponse]

// PtyService_ServiceDesc is the grpc.ServiceDesc for PtyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PtyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workspace.v1.PtyService",
	HandlerType: (*PtyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePty",
			Handler:    _PtyService_CreatePty_Handler,
		},
		{
			MethodName: "ResizePty",
			Handler:    _PtyService_ResizePty_Handler,
		},
		{
			MethodName: "KillPty",
			Handler:    _PtyService_KillPty_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PtyStream",
			Handler:       _PtyService_PtyStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "workspace/v1/pty.proto",
}
