// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workspace/v1/sandbox.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sandbox state enumeration
type SandboxState int32

const (
	SandboxState_SANDBOX_STATE_UNSPECIFIED SandboxState = 0
	SandboxState_SANDBOX_STATE_STARTING    SandboxState = 1
	SandboxState_SANDBOX_STATE_RUNNING     SandboxState = 2
	SandboxState_SANDBOX_STATE_STOPPING    SandboxState = 3
	SandboxState_SANDBOX_STATE_STOPPED     SandboxState = 4
	SandboxState_SANDBOX_STATE_ERROR       SandboxState = 5
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0: "SANDBOX_STATE_UNSPECIFIED",
		1: "SANDBOX_STATE_STARTING",
		2: "SANDBOX_STATE_RUNNING",
		3: "SANDBOX_STATE_STOPPING",
		4: "SANDBOX_STATE_STOPPED",
		5: "SANDBOX_STATE_ERROR",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_UNSPECIFIED": 0,
		"SANDBOX_STATE_STARTING":    1,
		"SANDBOX_STATE_RUNNING":     2,
		"SANDBOX_STATE_STOPPING":    3,
		"SANDBOX_STATE_STOPPED":     4,
		"SANDBOX_STATE_ERROR":       5,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_workspace_v1_sandbox_proto_enumTypes[0].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_workspace_v1_sandbox_proto_enumTypes[0]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_workspace_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

// Sandbox resource
type Sandbox struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Workspace ID this sandbox is bound to
	WorkspaceId string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Optional human-readable name
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Template used to create this sandbox
	Template string `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`
	// Current state
	State SandboxState `protobuf:"varint,5,opt,name=state,proto3,enum=workspace.v1.SandboxState" json:"state,omitempty"`
	// Environment variables
	Env map[string]string `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Custom metadata
	Metadata map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Timeout in seconds (0 = no timeout)
	Timeout uint64 `protobuf:"varint,10,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Error message (if state is ERROR)
	ErrorMessage  *string `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sandbox) Reset() {
	*x = Sandbox{}
	mi := &file_workspace_v1_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sandbox) ProtoMessage() {}

func (x *Sandbox) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sandbox.ProtoReflect.Descriptor instead.
func (*Sandbox) Descriptor() ([]byte, []int) {
	return file_workspace_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *Sandbox) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sandbox) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Sandbox) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Sandbox) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Sandbox) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

func (x *Sandbox) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Sandbox) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Sandbox) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Sandbox) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Sandbox) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Sandbox) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// Create sandbox request
type CreateSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workspace ID to bind to (required)
	WorkspaceId string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Template to use (optional, defaults to "default")
	Template *string `protobuf:"bytes,2,opt,name=template,proto3,oneof" json:"template,omitempty"`
	// Optional name
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Environment variables
	Env map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Custom metadata
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timeout in seconds (optional)
	Timeout       *uint64 `protobuf:"varint,6,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_workspace_v1_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateSandboxRequest) GetTemplate() string {
	if x != nil && x.Template != nil {
		return *x.Template
	}
	return ""
}

func (x *CreateSandboxRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateSandboxRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateSandboxRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateSandboxRequest) GetTimeout() uint64 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

// Create sandbox response
type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_workspace_v1_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSandboxResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

// Get sandbox request
type GetSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_workspace_v1_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *GetSandboxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Get sandbox response
type GetSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxResponse) Reset() {
	*x = GetSandboxResponse{}
	mi := &file_workspace_v1_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxResponse) ProtoMessage() {}

func (x *GetSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *GetSandboxResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

// List sandboxes request
type ListSandboxesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by state (optional)
	State *SandboxState `protobuf:"varint,1,opt,name=state,proto3,enum=workspace.v1.SandboxState,oneof" json:"state,omitempty"`
	// Pagination: page size
	PageSize *int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// Pagination: page token
	PageToken     *string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_workspace_v1_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *ListSandboxesRequest) GetState() SandboxState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

func (x *ListSandboxesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListSandboxesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

// List sandboxes response
type ListSandboxesResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes []*Sandbox             `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	// Next page token (empty if no more pages)
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count
	Total         int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_workspace_v1_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *ListSandboxesResponse) GetSandboxes() []*Sandbox {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

func (x *ListSandboxesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListSandboxesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Delete sandbox request
type DeleteSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Force delete even if running
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxRequest) Reset() {
	*x = DeleteSandboxRequest{}
	mi := &file_workspace_v1_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxRequest) ProtoMessage() {}

func (x *DeleteSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxRequest.ProtoReflect.Descriptor instead.
func (*DeleteSandboxRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSandboxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteSandboxRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Delete sandbox response
type DeleteSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxResponse) Reset() {
	*x = DeleteSandboxResponse{}
	mi := &file_workspace_v1_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxResponse) ProtoMessage() {}

func (x *DeleteSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxResponse.ProtoReflect.Descriptor instead.
func (*DeleteSandboxResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_workspace_v1_sandbox_proto protoreflect.FileDescriptor

const file_workspace_v1_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x1aworkspace/v1/sandbox.proto\x12\fworkspace.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x04\n" +
	"\aSandbox\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1a\n" +
	"\btemplate\x18\x04 \x01(\tR\btemplate\x120\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1a.workspace.v1.SandboxStateR\x05state\x120\n" +
	"\x03env\x18\x06 \x03(\v2\x1e.workspace.v1.Sandbox.EnvEntryR\x03env\x12?\n" +
	"\bmetadata\x18\a \x03(\v2#.workspace.v1.Sandbox.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\atimeout\x18\n" +
	" \x01(\x04R\atimeout\x12(\n" +
	"\rerror_message\x18\v \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_nameB\x10\n" +
	"\x0e_error_message\"\xb6\x03\n" +
	"\x14CreateSandboxRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\btemplate\x18\x02 \x01(\tH\x00R\btemplate\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12=\n" +
	"\x03env\x18\x04 \x03(\v2+.workspace.v1.CreateSandboxRequest.EnvEntryR\x03env\x12L\n" +
	"\bmetadata\x18\x05 \x03(\v20.workspace.v1.CreateSandboxRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\atimeout\x18\x06 \x01(\x04H\x02R\atimeout\x88\x01\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_templateB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_timeout\"H\n" +
	"\x15CreateSandboxResponse\x12/\n" +
	"\asandbox\x18\x01 \x01(\v2\x15.workspace.v1.SandboxR\asandbox\"#\n" +
	"\x11GetSandboxRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x12GetSandboxResponse\x12/\n" +
	"\asandbox\x18\x01 \x01(\v2\x15.workspace.v1.SandboxR\asandbox\"\xba\x01\n" +
	"\x14ListSandboxesRequest\x125\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1a.workspace.v1.SandboxStateH\x00R\x05state\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x02R\tpageToken\x88\x01\x01B\b\n" +
	"\x06_stateB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x8a\x01\n" +
	"\x15ListSandboxesResponse\x123\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x15.workspace.v1.SandboxR\tsandboxes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"<\n" +
	"\x14DeleteSandboxRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"1\n" +
	"\x15DeleteSandboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xb4\x01\n" +
	"\fSandboxState\x12\x1d\n" +
	"\x19SANDBOX_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SANDBOX_STATE_STARTING\x10\x01\x12\x19\n" +
	"\x15SANDBOX_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16SANDBOX_STATE_STOPPING\x10\x03\x12\x19\n" +
	"\x15SANDBOX_STATE_STOPPED\x10\x04\x12\x17\n" +
	"\x13SANDBOX_STATE_ERROR\x10\x052\xef\x02\n" +
	"\x0eSandboxService\x12X\n" +
	"\rCreateSandbox\x12\".workspace.v1.CreateSandboxRequest\x1a#.workspace.v1.CreateSandboxResponse\x12O\n" +
	"\n" +
	"GetSandbox\x12\x1f.workspace.v1.GetSandboxRequest\x1a .workspace.v1.GetSandboxResponse\x12X\n" +
	"\rListSandboxes\x12\".workspace.v1.ListSandboxesRequest\x1a#.workspace.v1.ListSandboxesResponse\x12X\n" +
	"\rDeleteSandbox\x12\".workspace.v1.DeleteSandboxRequest\x1a#.workspace.v1.DeleteSandboxResponseB6Z4github.com/OpenElevo/ElevoSandbox/proto/workspace/v1b\x06proto3"

var (
	file_workspace_v1_sandbox_proto_rawDescOnce sync.Once
	file_workspace_v1_sandbox_proto_rawDescData []byte
)

func file_workspace_v1_sandbox_proto_rawDescGZIP() []byte {
	file_workspace_v1_sandbox_proto_rawDescOnce.Do(func() {
		file_workspace_v1_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_sandbox_proto_rawDesc), len(file_workspace_v1_sandbox_proto_rawDesc)))
	})
	return file_workspace_v1_sandbox_proto_rawDescData
}

var file_workspace_v1_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workspace_v1_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_workspace_v1_sandbox_proto_goTypes = []any{
	(SandboxState)(0),             // 0: workspace.v1.SandboxState
	(*Sandbox)(nil),               // 1: workspace.v1.Sandbox
	(*CreateSandboxRequest)(nil),  // 2: workspace.v1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil), // 3: workspace.v1.CreateSandboxResponse
	(*GetSandboxRequest)(nil),     // 4: workspace.v1.GetSandboxRequest
	(*GetSandboxResponse)(nil),    // 5: workspace.v1.GetSandboxResponse
	(*ListSandboxesRequest)(nil),  // 6: workspace.v1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil), // 7: workspace.v1.ListSandboxesResponse
	(*DeleteSandboxRequest)(nil),  // 8: workspace.v1.DeleteSandboxRequest
	(*DeleteSandboxResponse)(nil), // 9: workspace.v1.DeleteSandboxResponse
	nil,                           // 10: workspace.v1.Sandbox.EnvEntry
	nil,                           // 11: workspace.v1.Sandbox.MetadataEntry
	nil,                           // 12: workspace.v1.CreateSandboxRequest.EnvEntry
	nil,                           // 13: workspace.v1.CreateSandboxRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_workspace_v1_sandbox_proto_depIdxs = []int32{
	0,  // 0: workspace.v1.Sandbox.state:type_name -> workspace.v1.SandboxState
	10, // 1: workspace.v1.Sandbox.env:type_name -> workspace.v1.Sandbox.EnvEntry
	11, // 2: workspace.v1.Sandbox.metadata:type_name -> workspace.v1.Sandbox.MetadataEntry
	14, // 3: workspace.v1.Sandbox.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: workspace.v1.Sandbox.updated_at:type_name -> google.protobuf.Timestamp
	12, // 5: workspace.v1.CreateSandboxRequest.env:type_name -> workspace.v1.CreateSandboxRequest.EnvEntry
	13, // 6: workspace.v1.CreateSandboxRequest.metadata:type_name -> workspace.v1.CreateSandboxRequest.MetadataEntry
	1,  // 7: workspace.v1.CreateSandboxResponse.sandbox:type_name -> workspace.v1.Sandbox
	1,  // 8: workspace.v1.GetSandboxResponse.sandbox:type_name -> workspace.v1.Sandbox
	0,  // 9: workspace.v1.ListSandboxesRequest.state:type_name -> workspace.v1.SandboxState
	1,  // 10: workspace.v1.ListSandboxesResponse.sandboxes:type_name -> workspace.v1.Sandbox
	2,  // 11: workspace.v1.SandboxService.CreateSandbox:input_type -> workspace.v1.CreateSandboxRequest
	4,  // 12: workspace.v1.SandboxService.GetSandbox:input_type -> workspace.v1.GetSandboxRequest
	6,  // 13: workspace.v1.SandboxService.ListSandboxes:input_type -> workspace.v1.ListSandboxesRequest
	8,  // 14: workspace.v1.SandboxService.DeleteSandbox:input_type -> workspace.v1.DeleteSandboxRequest
	3,  // 15: workspace.v1.SandboxService.CreateSandbox:output_type -> workspace.v1.CreateSandboxResponse
	5,  // 16: workspace.v1.SandboxService.GetSandbox:output_type -> workspace.v1.GetSandboxResponse
	7,  // 17: workspace.v1.SandboxService.ListSandboxes:output_type -> workspace.v1.ListSandboxesResponse
	9,  // 18: workspace.v1.SandboxService.DeleteSandbox:output_type -> workspace.v1.DeleteSandboxResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_workspace_v1_sandbox_proto_init() }
func file_workspace_v1_sandbox_proto_init() {
	if File_workspace_v1_sandbox_proto != nil {
		return
	}
	file_workspace_v1_sandbox_proto_msgTypes[0].OneofWrappers = []any{}
	file_workspace_v1_sandbox_proto_msgTypes[1].OneofWrappers = []any{}
	file_workspace_v1_sandbox_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_sandbox_proto_rawDesc), len(file_workspace_v1_sandbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_sandbox_proto_goTypes,
		DependencyIndexes: file_workspace_v1_sandbox_proto_depIdxs,
		EnumInfos:         file_workspace_v1_sandbox_proto_enumTypes,
		MessageInfos:      file_workspace_v1_sandbox_proto_msgTypes,
	}.Build()
	File_workspace_v1_sandbox_proto = out.File
	file_workspace_v1_sandbox_proto_goTypes = nil
	file_workspace_v1_sandbox_proto_depIdxs = nil
}
